/** What a username is replaced with in every text that leaves the server. */
export const USERNAME_MASK = "[REDACTED:account-username]";

/** Run ids are generated by newRunId(); anything else is never looked up on disk. */
export const RUN_ID = /^[\w-]+$/;

/** Spec and report file names we are willing to serve: a plain base name, never "." or ".." segments. */
export const SAFE_FILE = /^[\w-][\w.-]*$/;

/** A redacted secret in a URL, as redactSecrets writes it: "[REDACTED:github-token]". */
export const REDACTED = /\[REDACTED:[\w-]*\]/;

/** Evidence files served next to report.html: annotated frames and cards (PNG) and recordings (GIF). */
export const ARTIFACT_TYPES: Record<string, string> = {
  ".png": "image/png",
  ".gif": "image/gif",
};

/** Content types for the report files /api/runs/:id/ serves. */
export const REPORT_FILES: Record<string, string> = {
  "report.json": "application/json; charset=utf-8",
  "report.md": "text/markdown; charset=utf-8",
  "report.html": "text/html; charset=utf-8",
};

/** Security headers on every response: never framed, never MIME-sniffed, no Referer to other sites. */
export const BASE_HEADERS: Record<string, string> = {
  "x-content-type-options": "nosniff",
  "x-frame-options": "DENY",
  "referrer-policy": "no-referrer",
};

/** Default CSP: allows nothing. The UI and report.html get their own policies. */
export const DEFAULT_CSP =
  "default-src 'none'; frame-ancestors 'none'; base-uri 'none'; form-action 'none'";

/** CSP for report.html: no scripts, opaque origin, sandbox; inline styles and own images still load. */
export const REPORT_CSP =
  "default-src 'none'; img-src 'self' data:; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'; " +
  "sandbox allow-popups allow-popups-to-escape-sandbox";