import { randomUUID } from "node:crypto";
import { readFile, stat } from "node:fs/promises";
import { isIP } from "node:net";
import { join, resolve } from "node:path";
import { Hono } from "hono";
import type { Check, Plan, Report } from "../core/types.js";
import { cleanErrorMessage, NoFormFoundError, TargetNotAllowedError, TargetUnreachableError } from "../engine/errors.js";
import { redactSecrets } from "../engine/redact.js";
import { discoverAndPlan, newRunId, runPlan, type ProgressEvent, type RunOptions } from "../engine/runner.js";

export interface ServerOptions extends Pick<RunOptions, "checks" | "runsDir" | "allowedHosts"> {
  /** Runs allowed at the same time (each one drives its own Chromium). Default 2; more are refused with 409. */
  maxConcurrentRuns?: number;
  /**
   * Extra host names this server answers to, besides loopback ones (RUNHOUND_SERVER_HOSTS).
   * Everything else is refused, so a public domain that resolves to 127.0.0.1 (DNS rebinding) can't
   * drive Run Hound from a web page.
   */
  serverHosts?: string[];
}

interface RunState {
  status: "running" | "done" | "error";
  completed: number;
  total: number;
  dir: string;
  report?: Report;
  error?: string;
  live: LiveState;
}

/** What GET /api/runs/:id/live returns, plus the latest frame (served separately as live.jpg). */
interface LiveState {
  scenarioId: string | null;
  scenarioTitle: string | null;
  step: string | null;
  url: string | null;
  /** Counts frames received, so the UI only reloads live.jpg when there is a new one. */
  frameSeq: number;
  updatedAt: string;
  steps: { scenarioId: string; label: string; url: string; at: string }[];
  pagesVisited: string[];
  /** Only the latest frame is kept; it survives the end of the run so the UI can keep showing it. */
  frame?: Buffer;
}

/** How many steps the live log keeps (oldest dropped first). */
const LIVE_STEPS = 100;

function newLiveState(): LiveState {
  return { scenarioId: null, scenarioTitle: null, step: null, url: null, frameSeq: 0, updatedAt: new Date().toISOString(), steps: [], pagesVisited: [] };
}

/** Folds one runner progress event into the live state. URLs and labels arrive already redacted by the engine. */
function applyProgress(live: LiveState, plan: Plan, e: ProgressEvent): void {
  live.updatedAt = new Date().toISOString();
  switch (e.type) {
    case "scenario-start":
      live.scenarioId = e.scenarioId;
      live.scenarioTitle = plan.scenarios.find((s) => s.id === e.scenarioId)?.title ?? null;
      live.step = null;
      break;
    case "step":
      live.step = e.label;
      live.url = e.url;
      live.steps.push({ scenarioId: e.scenarioId, label: e.label, url: e.url, at: e.at });
      if (live.steps.length > LIVE_STEPS) live.steps.splice(0, live.steps.length - LIVE_STEPS);
      break;
    case "page":
      live.url = e.url;
      if (!live.pagesVisited.includes(e.url)) live.pagesVisited.push(e.url);
      break;
    case "frame":
      live.frame = e.jpeg;
      live.frameSeq += 1;
      break;
    case "scenario-end":
      break;
  }
}

/** Evidence files served next to report.html: annotated frames and cards (PNG) and recordings (GIF). */
const ARTIFACT_TYPES: Record<string, string> = { ".png": "image/png", ".gif": "image/gif" };

/** Spec and report file names we are willing to serve: a plain base name, never "." or ".." segments. */
const SAFE_FILE = /^[\w-][\w.-]*$/;

const REPORT_FILES: Record<string, string> = {
  "report.json": "application/json; charset=utf-8",
  "report.md": "text/markdown; charset=utf-8",
  "report.html": "text/html; charset=utf-8",
};

/**
 * Hosts the UI and API answer to without being listed: loopback names and any IP literal (so reaching the
 * container or a LAN address by IP still works). A DNS rebinding attack always arrives under a NAME the
 * attacker controls, which lands here and is refused.
 */
function isDefaultHost(host: string): boolean {
  const name = host.replace(/^\[|\]$/g, "").toLowerCase();
  return name === "localhost" || name.endsWith(".localhost") || isIP(name) !== 0;
}

/** Errors caused by the user's input (bad or refused URL, no form, page won't load) rather than by Run Hound. */
function isUserError(err: unknown): boolean {
  return (
    err instanceof TargetNotAllowedError ||
    err instanceof NoFormFoundError ||
    err instanceof TargetUnreachableError ||
    (err instanceof Error && /net::ERR_|Timeout .*exceeded/.test(err.message))
  );
}

/** Plans and finished runs kept in memory; the oldest are dropped first (finished runs stay readable from disk). */
const MAX_PLANS = 50;
const MAX_RUNS = 50;

/** Run ids are generated by newRunId(); anything else is never looked up on disk. */
const RUN_ID = /^[\w-]+$/;

/** Check titles for the plan's fieldset legends, e.g. {"dead-control": "Every button does something"}. */
async function checkTitles(checks: Check[] | undefined): Promise<Record<string, string>> {
  const list = checks ?? (await import("../checks/index.js")).checks;
  return Object.fromEntries(list.map((c) => [c.id, c.title]));
}

/**
 * Local UI + JSON API (served on port 4000 by the CLI):
 *   GET  /                          HTML UI: target URL -> plan with checkboxes -> approve -> progress -> report
 *   POST /api/plan  {url}           200 {planId, plan, checks: {checkId: title}} | 400 {error} (bad URL, not allowed,
 *                                   unreachable, no form). "localhost:3000/book" is read as http://localhost:3000/book.
 *   POST /api/runs  {planId, approved: string[], allowDestructive?: boolean, headed?: boolean}  202 {runId}
 *                                   | 404 unknown plan | 400 empty approval, unknown scenario ids or a non-boolean flag
 *                                   | 409 too many runs in progress (maxConcurrentRuns)
 *   GET  /api/runs/:runId           {status: "running"|"done"|"error", completed, total, report?, error?}
 *   GET  /api/runs/:runId/report.json | report.md | report.html
 *   GET  /api/runs/:runId/specs/:file
 *   GET  /api/runs/:runId/artifacts/:file   evidence images (PNG) and recordings (GIF) referenced by report.html
 *   GET  /api/runs/:runId/live       {status, scenarioId, scenarioTitle, step, url, frameSeq, updatedAt,
 *                                     steps: [{scenarioId, label, url, at}] (last 100), pagesVisited: string[]}
 *   GET  /api/runs/:runId/live.jpg   latest frame of the browser under test (image/jpeg, no-store); 404 before the first frame
 * POST /api/runs also accepts {headed?: boolean} to open a visible browser window on the machine running Run Hound.
 * While a run is in progress the UI shows a live view: the page URL, the current scenario and step, the latest
 * frame (refreshed about twice a second), the step log and the list of pages being tested.
 * Plans and run states live in memory (the newest 50 of each); a finished run that is no longer in memory, or was
 * written before a restart, is read back from runsDir/<runId>/report.json, so report links keep working.
 * The UI keeps the run id in the page's #run=<id> fragment, so reloading the page shows the same run.
 */
export function createApp(options: ServerOptions = {}): Hono {
  const app = new Hono();
  const plans = new Map<string, Plan>();
  const runs = new Map<string, RunState>();
  const runsDir = resolve(options.runsDir ?? "runs");
  const extraHosts = (options.serverHosts ?? (process.env.RUNHOUND_SERVER_HOSTS ?? "").split(","))
    .map((h) => h.trim().toLowerCase())
    .filter(Boolean);
  const hostAllowed = (host: string) => isDefaultHost(host) || extraHosts.includes(host.toLowerCase());
  const maxRuns = options.maxConcurrentRuns ?? 2;

  /** Drops the oldest entries (Maps keep insertion order); running runs are never dropped. */
  function prune(): void {
    for (const id of [...plans.keys()].slice(0, Math.max(0, plans.size - MAX_PLANS))) plans.delete(id);
    const finished = [...runs].filter(([, r]) => r.status !== "running").map(([id]) => id);
    for (const id of finished.slice(0, Math.max(0, runs.size - MAX_RUNS))) runs.delete(id);
  }

  /** The run's state from memory, or a finished run read back from disk (after a restart or pruning). */
  async function runState(runId: string): Promise<RunState | undefined> {
    const known = runs.get(runId);
    if (known || !RUN_ID.test(runId)) return known;
    const dir = join(runsDir, runId);
    try {
      if (!(await stat(dir)).isDirectory()) return undefined;
      const report = JSON.parse(await readFile(join(dir, "report.json"), "utf8")) as Report;
      if (report.runId !== runId) return undefined;
      const live = newLiveState();
      live.pagesVisited = (report.pagesVisited ?? []).map((p) => p.url);
      return { status: "done", completed: report.results.length, total: report.results.length, dir, report, live };
    } catch {
      return undefined;
    }
  }

  // Only answer requests addressed to this machine, and never act on a POST from another site.
  app.use("*", async (c, next) => {
    const { hostname, origin } = new URL(c.req.url);
    if (!hostAllowed(hostname)) {
      return c.json(
        { error: `Run Hound does not answer to the host name "${hostname}". Set RUNHOUND_SERVER_HOSTS=${hostname} if you meant to use it.` },
        403,
      );
    }
    const sent = c.req.header("origin");
    if (sent && sent !== origin && c.req.method !== "GET" && c.req.method !== "HEAD") {
      return c.json({ error: "Cross-site requests are not allowed." }, 403);
    }
    await next();
  });

  app.get("/", (c) => c.html(UI_HTML));

  // Only accept JSON posts: a cross-site page can send text/plain without a CORS preflight, but not application/json.
  app.use("/api/*", async (c, next) => {
    if (c.req.method === "POST" && !(c.req.header("content-type") ?? "").toLowerCase().startsWith("application/json")) {
      return c.json({ error: "Send the request body as application/json." }, 415);
    }
    await next();
  });

  app.post("/api/plan", async (c) => {
    let body: unknown;
    try {
      body = await c.req.json();
    } catch {
      return c.json({ error: "The request body must be JSON like {\"url\": \"http://localhost:3000/\"}." }, 400);
    }
    const url = (body as { url?: unknown } | null)?.url;
    if (typeof url !== "string" || url.trim() === "") return c.json({ error: "Enter the URL of the page with your form." }, 400);

    try {
      const plan = await discoverAndPlan(url.trim(), { checks: options.checks, allowedHosts: options.allowedHosts });
      const planId = randomUUID();
      plans.set(planId, plan);
      prune();
      // The stored plan keeps the real target; what leaves the process is redacted.
      return c.json({ planId, plan: redactPlan(plan), checks: await checkTitles(options.checks) }, 200);
    } catch (err) {
      const message = redactSecrets(cleanErrorMessage(err instanceof Error ? err.message : String(err)));
      if (isUserError(err)) return c.json({ error: message }, 400);
      return c.json({ error: `Could not plan a run: ${message}` }, 500);
    }
  });

  app.post("/api/runs", async (c) => {
    let body: { planId?: unknown; approved?: unknown; allowDestructive?: unknown; headed?: unknown };
    try {
      body = ((await c.req.json()) ?? {}) as typeof body;
    } catch {
      return c.json({ error: "The request body must be JSON." }, 400);
    }
    const plan = typeof body.planId === "string" ? plans.get(body.planId) : undefined;
    if (!plan) return c.json({ error: "Unknown plan. Create a plan first." }, 404);
    if (body.approved !== undefined && !(Array.isArray(body.approved) && body.approved.every((a) => typeof a === "string"))) {
      return c.json({ error: "approved must be a list of scenario ids." }, 400);
    }
    for (const flag of ["allowDestructive", "headed"] as const) {
      if (body[flag] !== undefined && typeof body[flag] !== "boolean") return c.json({ error: `${flag} must be true or false.` }, 400);
    }

    const approved = body.approved as string[] | undefined;
    const unknown = (approved ?? []).filter((id) => !plan.scenarios.some((s) => s.id === id));
    if (unknown.length > 0) return c.json({ error: `Unknown scenario id(s): ${redactSecrets(unknown.join(", "))}.` }, 400);
    const approvedSet = new Set(approved ?? plan.scenarios.filter((s) => s.defaultSelected).map((s) => s.id));
    // An empty run would report "0 findings" and look like a clean pass.
    if (approvedSet.size === 0) return c.json({ error: "Select at least one scenario to run." }, 400);
    const running = [...runs.values()].filter((r) => r.status === "running").length;
    if (running >= maxRuns) {
      return c.json({ error: `${running} run${running === 1 ? " is" : "s are"} already in progress. Wait for ${running === 1 ? "it" : "one"} to finish.` }, 409);
    }
    const runId = newRunId();
    const state: RunState = {
      status: "running",
      completed: 0,
      total: plan.scenarios.filter((s) => approvedSet.has(s.id)).length,
      dir: join(runsDir, runId),
      live: newLiveState(),
    };
    runs.set(runId, state);
    prune();

    runPlan(plan, {
      checks: options.checks,
      allowedHosts: options.allowedHosts,
      runsDir,
      runId,
      approved,
      allowDestructive: body.allowDestructive === true,
      headed: body.headed === true,
      // The UI always shows the live view, so the server always asks for the screencast.
      live: true,
      onProgress: (e) => {
        if (e.type === "scenario-end") state.completed += 1;
        applyProgress(state.live, plan, e);
      },
    }).then(
      ({ report, dir }) => {
        Object.assign(state, { status: "done", report, dir });
        // The report is authoritative once written (it also covers pages seen before a frame or step).
        if (report.pagesVisited) state.live.pagesVisited = report.pagesVisited.map((p) => p.url);
        state.live.updatedAt = new Date().toISOString();
      },
      (err: unknown) => {
        Object.assign(state, { status: "error", error: redactSecrets(cleanErrorMessage(err instanceof Error ? err.message : String(err))) });
        state.live.updatedAt = new Date().toISOString();
      },
    );

    return c.json({ runId }, 202);
  });

  app.get("/api/runs/:runId", async (c) => {
    const state = await runState(c.req.param("runId"));
    if (!state) return c.json({ error: "Unknown run." }, 404);
    const { dir: _dir, live: _live, ...status } = state;
    return c.json(status);
  });

  app.get("/api/runs/:runId/live", async (c) => {
    const state = await runState(c.req.param("runId"));
    if (!state) return c.json({ error: "Unknown run." }, 404);
    const { frame: _frame, ...live } = state.live;
    return c.json({ status: state.status, ...live }, 200, { "cache-control": "no-store" });
  });

  // The latest screencast frame. Pixels can't be redacted, which is why this is only served on loopback-guarded hosts.
  app.get("/api/runs/:runId/live.jpg", (c) => {
    const frame = runs.get(c.req.param("runId"))?.live.frame;
    if (!frame) return c.json({ error: "No frame yet." }, 404);
    return c.body(new Uint8Array(frame), 200, { "content-type": "image/jpeg", "cache-control": "no-store" });
  });

  app.get("/api/runs/:runId/:file{report\\.(?:json|md|html)}", async (c) => {
    const state = await runState(c.req.param("runId"));
    const file = c.req.param("file");
    const type = REPORT_FILES[file];
    if (!state || state.status !== "done" || !type) return c.json({ error: "Not found." }, 404);
    return c.body(await readFile(join(state.dir, file), "utf8"), 200, { "content-type": type });
  });

  app.get("/api/runs/:runId/specs/:file", async (c) => {
    const state = await runState(c.req.param("runId"));
    if (!state || state.status !== "done") return c.json({ error: "Not found." }, 404);
    const file = c.req.param("file");
    if (!SAFE_FILE.test(file)) return c.json({ error: "Invalid file name." }, 400);
    try {
      const source = await readFile(join(state.dir, "specs", file), "utf8");
      return c.body(source, 200, { "content-type": "text/plain; charset=utf-8" });
    } catch {
      return c.json({ error: "Not found." }, 404);
    }
  });

  // Evidence referenced from report.html (artifacts/<file>.png|.gif), served next to the report.
  app.get("/api/runs/:runId/artifacts/:file", async (c) => {
    const state = await runState(c.req.param("runId"));
    const file = c.req.param("file");
    if (!state || state.status !== "done") return c.json({ error: "Not found." }, 404);
    const type = ARTIFACT_TYPES[file.slice(file.lastIndexOf(".")).toLowerCase()];
    if (!SAFE_FILE.test(file) || !type) return c.json({ error: "Invalid file name." }, 400);
    try {
      const bytes = await readFile(join(state.dir, "artifacts", file));
      return c.body(new Uint8Array(bytes), 200, { "content-type": type });
    } catch {
      return c.json({ error: "Not found." }, 404);
    }
  });

  app.notFound((c) => c.json({ error: "Not found." }, 404));

  return app;
}

/** A plan with secrets redacted (its target URL may carry a token). */
function redactPlan(plan: Plan): Plan {
  return JSON.parse(redactSecrets(JSON.stringify(plan))) as Plan;
}

/**
 * The single-page UI. Server-rendered shell plus a small inline script that talks to the JSON API.
 * Night Shift palette; every control is labelled, focus is always visible, progress goes to a live region.
 * The script builds DOM with textContent only, so report text is never parsed as HTML.
 */
const UI_HTML = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Run Hound</title>
<style>
:root { --bg:#0E1012; --surface:#171A1D; --text:#E8E6E1; --muted:#B4B8BC; --amber:#F5B642; --pass:#6FCF97; --fail:#FF7A6B; --line:#2A2F34; }
* { box-sizing: border-box; }
body { margin:0; background:var(--bg); color:var(--text); font:16px/1.5 system-ui, -apple-system, "Segoe UI", sans-serif; }
main { max-width: 52rem; margin: 0 auto; padding: 2rem 1rem 4rem; }
main.watching { max-width: 76rem; }
h1 { margin: 0; color: var(--amber); font-size: 1.75rem; }
h2 { font-size: 1.2rem; margin: 0 0 .75rem; }
p.lead, .muted { color: var(--muted); }
section.card { background: var(--surface); border: 1px solid var(--line); border-radius: 8px; padding: 1rem 1.25rem; margin-top: 1.25rem; }
label { display: block; font-weight: 600; margin-bottom: .35rem; }
.row { display: flex; gap: .5rem; flex-wrap: wrap; }
input[type=url] { flex: 1 1 16rem; min-width: 0; padding: .6rem .75rem; border-radius: 6px; border: 1px solid #4A5057; background: var(--bg); color: var(--text); font: inherit; }
button { padding: .6rem 1.1rem; border-radius: 6px; border: 0; background: var(--amber); color: #0E1012; font: inherit; font-weight: 700; cursor: pointer; min-height: 44px; }
button:disabled { opacity: .6; cursor: progress; }
:focus-visible { outline: 3px solid var(--amber); outline-offset: 2px; }
input[type=url]:focus-visible { outline-offset: 0; }
fieldset { border: 1px solid var(--line); border-radius: 6px; margin: 0 0 .75rem; padding: .5rem .75rem; }
legend { color: var(--amber); font-weight: 600; padding: 0 .25rem; }
.scenario { display: flex; gap: .6rem; align-items: flex-start; padding: .35rem 0; }
.scenario input { width: 1.25rem; height: 1.25rem; margin-top: .2rem; accent-color: var(--amber); flex: none; }
.scenario label { font-weight: 400; margin: 0; }
.scenario .desc { display: block; color: var(--muted); font-size: .9rem; }
.tag { font-size: .75rem; border: 1px solid var(--line); border-radius: 999px; padding: 0 .45rem; margin-left: .35rem; color: var(--muted); }
.tag.danger { color: var(--fail); border-color: var(--fail); }
.error { color: var(--fail); }
.pass { color: var(--pass); }
.fail { color: var(--fail); }
progress { width: 100%; height: .75rem; accent-color: var(--amber); }
.finding { border-left: 4px solid var(--fail); padding: .25rem .75rem; margin: .75rem 0; }
.finding h3 { margin: 0; font-size: 1rem; overflow-wrap: anywhere; }
.finding p { margin: .25rem 0; }
/* Evidence: each finding's frames, GIFs and cards inline, linked to the full-size file, with the data behind them. */
.evidence { display: grid; gap: .75rem; margin: .5rem 0; }
.evidence figure { margin: 0; border: 1px solid var(--line); border-radius: 6px; background: var(--bg); overflow: hidden; }
.evidence img { display: block; width: 100%; height: auto; max-height: 36rem; object-fit: contain; object-position: left top; background: #0B0E13; }
.evidence figcaption { padding: .4rem .6rem; font-size: .85rem; color: var(--muted); overflow-wrap: anywhere; }
.evidence figcaption b { color: var(--text); font-weight: 600; }
.evidence details { padding: 0 .6rem .5rem; font-size: .85rem; }
.evidence summary { cursor: pointer; color: var(--amber); }
.evidence dl { display: grid; grid-template-columns: minmax(8rem, max-content) minmax(0, 1fr); gap: .15rem .75rem; margin: .4rem 0 0; }
.evidence dt { color: var(--muted); }
.evidence dd { margin: 0; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; overflow-wrap: anywhere; white-space: pre-wrap; }
a { color: var(--amber); }
ul.links { padding-left: 1.2rem; }
[hidden] { display: none !important; }
/* Live view: a small browser window showing the page under test, with what is happening beside it. */
#live { display: grid; gap: 1rem; }
.live-top { display: flex; flex-wrap: wrap; align-items: center; gap: .5rem 1rem; }
#status { margin: 0; font-weight: 600; flex: 1 1 20rem; }
.live-top progress { flex: 1 1 12rem; }
.live-grid { display: grid; gap: 1rem; grid-template-columns: minmax(0, 1fr); }
@media (min-width: 60rem) { .live-grid { grid-template-columns: minmax(0, 1.9fr) minmax(16rem, 1fr); } }
.browser { margin: 0; border: 1px solid #3A4046; border-radius: 10px; overflow: hidden; background: #0A0B0D; box-shadow: 0 8px 24px rgb(0 0 0 / .35); }
.chrome { display: flex; align-items: center; gap: .6rem; padding: .5rem .75rem; background: #22262A; border-bottom: 1px solid #3A4046; }
.dots { display: flex; gap: .35rem; flex: none; }
.dots i { width: .7rem; height: .7rem; border-radius: 50%; background: #4A5057; }
.address { flex: 1; min-width: 0; display: flex; align-items: center; gap: .5rem; background: var(--bg); border: 1px solid #3A4046; border-radius: 999px; padding: .3rem .8rem; }
.address .label { font-size: .75rem; color: var(--muted); text-transform: uppercase; letter-spacing: .06em; flex: none; }
#live-url { font: .9rem/1.3 ui-monospace, "SFMono-Regular", Menlo, Consolas, monospace; color: var(--text); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; min-width: 0; }
.pill { flex: none; font-size: .75rem; font-weight: 700; letter-spacing: .06em; border-radius: 999px; padding: .15rem .55rem; border: 1px solid var(--line); color: var(--muted); }
.pill.on { color: #0E1012; background: var(--fail); border-color: var(--fail); }
.pill.on::before { content: ""; display: inline-block; width: .45rem; height: .45rem; border-radius: 50%; background: #0E1012; margin-right: .35rem; vertical-align: .05rem; animation: blink 1.2s steps(2, start) infinite; }
@keyframes blink { to { visibility: hidden; } }
@media (prefers-reduced-motion: reduce) { .pill.on::before { animation: none; } }
.viewport { position: relative; aspect-ratio: 1280 / 800; background: #0A0B0D; }
.viewport img { display: block; width: 100%; height: 100%; object-fit: contain; object-position: top center; }
.viewport .placeholder { position: absolute; inset: 0; display: grid; place-items: center; margin: 0; color: var(--muted); text-align: center; padding: 1rem; }
.now { display: flex; gap: .6rem; align-items: baseline; padding: .55rem .8rem; background: #22262A; border-top: 1px solid #3A4046; }
.now .label { color: var(--amber); font-size: .75rem; font-weight: 700; text-transform: uppercase; letter-spacing: .06em; flex: none; }
#live-step { overflow-wrap: anywhere; }
.side { display: grid; gap: 1rem; align-content: start; min-width: 0; }
.side h3 { margin: 0 0 .4rem; font-size: .8rem; text-transform: uppercase; letter-spacing: .08em; color: var(--muted); }
.side .box { background: var(--bg); border: 1px solid var(--line); border-radius: 8px; padding: .6rem .75rem; }
#live-scenario { margin: 0; font-weight: 600; overflow-wrap: anywhere; }
#live-scenario-id { margin: .1rem 0 0; font: .8rem ui-monospace, Menlo, Consolas, monospace; color: var(--muted); overflow-wrap: anywhere; }
#live-pages { list-style: none; margin: 0; padding: 0; display: grid; gap: .3rem; }
#live-pages li { font: .85rem/1.35 ui-monospace, Menlo, Consolas, monospace; overflow-wrap: anywhere; padding-left: 1rem; position: relative; color: var(--muted); }
#live-pages li::before { content: ""; position: absolute; left: .1rem; top: .45rem; width: .45rem; height: .45rem; border-radius: 50%; border: 1px solid var(--muted); }
#live-pages li.current { color: var(--text); }
#live-pages li.current::before { background: var(--amber); border-color: var(--amber); }
#live-pages .tag { font-family: system-ui, sans-serif; color: var(--amber); border-color: var(--amber); }
.steps-scroll { max-height: 20rem; overflow: auto; margin: 0 -.75rem -.6rem; padding: 0 .75rem .6rem; }
#live-steps { margin: 0; padding: 0; list-style: none; display: grid; gap: .15rem; font-size: .88rem; }
#live-steps li { display: grid; grid-template-columns: auto 1fr; gap: 0 .6rem; padding: .2rem 0; border-bottom: 1px solid #1F2327; }
#live-steps li:last-child { border-bottom: 0; color: var(--amber); }
#live-steps time { font: .78rem/1.6 ui-monospace, Menlo, Consolas, monospace; color: var(--muted); }
#live-steps .url { grid-column: 2; font: .75rem ui-monospace, Menlo, Consolas, monospace; color: var(--muted); overflow-wrap: anywhere; }
#live-steps .scn { grid-column: 1 / -1; margin-top: .4rem; font-size: .75rem; font-weight: 700; color: var(--muted); text-transform: uppercase; letter-spacing: .06em; }
.empty { color: var(--muted); font-size: .88rem; margin: 0; }
@media (max-width: 40rem) {
  .dots, .address .label { display: none; }
  #live-url { white-space: normal; overflow-wrap: anywhere; }
  .address { border-radius: 8px; }
}
</style>
</head>
<body>
<main>
<header>
<h1>Run Hound</h1>
<p class="lead">Point it at a form on your own local app. It plans a set of checks, you approve them, it runs them in a real browser.</p>
</header>

<section class="card" aria-labelledby="step-target">
<h2 id="step-target">1. Target</h2>
<form id="target-form" novalidate>
<label for="target-url">Page URL (localhost or a private address)</label>
<div class="row">
<input id="target-url" name="url" type="url" required placeholder="http://localhost:3000/book" autocomplete="url" aria-describedby="target-error">
<button id="plan-button" type="submit">Plan checks</button>
</div>
<p id="target-error" class="error" role="alert"></p>
</form>
</section>

<section class="card" id="plan-section" aria-labelledby="step-plan" hidden>
<h2 id="step-plan">2. Approve the plan</h2>
<p class="muted" id="plan-summary"></p>
<form id="plan-form">
<div id="scenarios"></div>
<div class="scenario">
<input id="allow-destructive" type="checkbox">
<label for="allow-destructive">Allow destructive scenarios<span class="desc">They may change or delete data beyond creating test records. Leave off unless this is a throwaway environment.</span></label>
</div>
<div class="scenario">
<input id="headed" type="checkbox">
<label for="headed">Show the browser window<span class="desc">Opens a visible Chromium window on the machine running Run Hound (it needs a display). The live view below works either way.</span></label>
</div>
<p id="plan-error" class="error" role="alert"></p>
<button id="run-button" type="submit">Run approved checks</button>
</form>
</section>

<section class="card" id="progress-section" aria-labelledby="step-progress" hidden>
<h2 id="step-progress">3. Watch the run</h2>
<div id="live">
<div class="live-top">
<p id="status" role="status" aria-live="polite"></p>
<progress id="progress" max="1" value="0" aria-label="Scenarios completed"></progress>
</div>
<div class="live-grid">
<figure class="browser" aria-labelledby="live-caption">
<div class="chrome">
<span class="dots" aria-hidden="true"><i></i><i></i><i></i></span>
<div class="address"><span class="label" id="live-url-label">Testing</span><span id="live-url">Waiting for the browser…</span></div>
<span id="live-badge" class="pill">Starting</span>
</div>
<div class="viewport">
<img id="live-frame" alt="Live view of the browser under test. No frame yet." hidden>
<p id="live-placeholder" class="placeholder">Starting the browser…</p>
</div>
<figcaption class="now" id="live-caption"><span class="label">Now</span><span id="live-step">Starting the run</span></figcaption>
</figure>
<div class="side">
<section class="box" aria-labelledby="live-scenario-h">
<h3 id="live-scenario-h">Scenario</h3>
<p id="live-scenario">Not started</p>
<p id="live-scenario-id"></p>
</section>
<section class="box" aria-labelledby="live-pages-h">
<h3 id="live-pages-h">Pages tested</h3>
<ul id="live-pages"><li class="empty">None yet</li></ul>
</section>
<section class="box" aria-labelledby="live-steps-h">
<h3 id="live-steps-h">Steps (latest last)</h3>
<div class="steps-scroll" id="live-steps-box" tabindex="0" role="region" aria-labelledby="live-steps-h"><ol id="live-steps"></ol></div>
</section>
</div>
</div>
</div>
</section>

<section class="card" id="report-section" aria-labelledby="step-report" tabindex="-1" hidden>
<h2 id="step-report">4. Report</h2>
<div id="report"></div>
</section>
</main>
<script>
(() => {
  const $ = (id) => document.getElementById(id);
  const el = (tag, props = {}, ...children) => {
    const node = Object.assign(document.createElement(tag), props);
    for (const c of children) node.append(c);
    return node;
  };
  let planId = null;
  let checkTitles = {};
  const SEVERITY_ORDER = { critical: 0, high: 1, medium: 2, low: 3 };

  async function api(path, body) {
    const res = await fetch(path, body === undefined ? {} : { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) });
    const json = await res.json().catch(() => ({}));
    if (!res.ok) throw new Error(json.error || ("Request failed (" + res.status + ")"));
    return json;
  }

  $("target-form").addEventListener("submit", async (event) => {
    event.preventDefault();
    const url = $("target-url").value.trim();
    $("target-error").textContent = "";
    $("target-url").removeAttribute("aria-invalid");
    if (!url) {
      $("target-url").setAttribute("aria-invalid", "true");
      $("target-error").textContent = "Enter the URL of the page with your form.";
      $("target-url").focus();
      return;
    }
    $("plan-button").disabled = true;
    $("plan-button").textContent = "Opening the page…";
    try {
      const { planId: id, plan, checks } = await api("/api/plan", { url });
      planId = id;
      checkTitles = checks || {};
      showPlan(plan);
    } catch (err) {
      // A failed plan must not leave the previous target's plan on screen, ready to run.
      planId = null;
      $("plan-section").hidden = true;
      $("target-url").setAttribute("aria-invalid", "true");
      $("target-error").textContent = err.message;
    } finally {
      $("plan-button").disabled = false;
      $("plan-button").textContent = "Plan checks";
    }
  });

  function showPlan(plan) {
    const box = $("scenarios");
    box.replaceChildren();
    const fields = plan.form.fields.length;
    $("plan-summary").textContent = "Found " + (plan.form.name ? "“" + plan.form.name + "”" : "a form") + " with " + fields + " field" + (fields === 1 ? "" : "s") + ". " + plan.scenarios.length + " scenarios proposed.";
    const byCheck = new Map();
    for (const s of plan.scenarios) byCheck.set(s.checkId, [...(byCheck.get(s.checkId) || []), s]);
    for (const [checkId, scenarios] of byCheck) {
      const fs = el("fieldset", {}, el("legend", { textContent: checkTitles[checkId] || checkId }));
      for (const s of scenarios) {
        const id = "sc-" + s.id.replace(/[^\\w-]/g, "_");
        const input = el("input", { type: "checkbox", id, value: s.id, checked: s.defaultSelected });
        const label = el("label", { htmlFor: id }, s.title, el("span", { className: "tag" + (s.kind === "danger" ? " danger" : ""), textContent: s.kind }));
        if (s.destructive) label.append(el("span", { className: "tag danger", textContent: "destructive" }));
        label.append(el("span", { className: "desc", textContent: s.description }));
        fs.append(el("div", { className: "scenario" }, input, label));
      }
      box.append(fs);
    }
    $("plan-section").hidden = false;
    $("progress-section").hidden = true;
    $("report-section").hidden = true;
    $("step-plan").setAttribute("tabindex", "-1");
    $("step-plan").focus();
  }

  $("plan-form").addEventListener("submit", async (event) => {
    event.preventDefault();
    const approved = [...$("scenarios").querySelectorAll("input:checked")].map((i) => i.value);
    $("plan-error").textContent = "";
    if (!planId) {
      $("plan-error").textContent = "Plan the checks for a page first.";
      return;
    }
    if (approved.length === 0) {
      $("plan-error").textContent = "Select at least one scenario to run.";
      return;
    }
    $("run-button").disabled = true;
    $("progress-section").hidden = false;
    $("report-section").hidden = true;
    $("status").textContent = "Starting " + approved.length + " scenarios…";
    try {
      const { runId } = await api("/api/runs", { planId, approved, allowDestructive: $("allow-destructive").checked, headed: $("headed").checked });
      resetLive($("headed").checked);
      // Keeps the run in the address, so reloading the page comes back to it.
      history.replaceState(null, "", "#run=" + encodeURIComponent(runId));
      poll(runId);
    } catch (err) {
      $("status").textContent = "Could not start the run: " + err.message;
      $("run-button").disabled = false;
    }
  });

  const time = (iso) => new Date(iso).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", second: "2-digit", hourCycle: "h23" });

  function resetLive(headed) {
    document.querySelector("main").classList.add("watching");
    $("live-url").textContent = "Waiting for the browser…";
    $("live-url-label").textContent = "Testing";
    $("live-scenario-h").textContent = "Scenario";
    $("live-step").textContent = headed ? "Opening a browser window on this machine" : "Starting the browser";
    $("live-scenario").textContent = "Not started";
    $("live-scenario-id").textContent = "";
    $("live-pages").replaceChildren(el("li", { className: "empty", textContent: "None yet" }));
    $("live-steps").replaceChildren();
    $("live-frame").hidden = true;
    $("live-frame").removeAttribute("src");
    $("live-placeholder").hidden = false;
    $("live-placeholder").textContent = "Starting the browser…";
    setBadge("Starting", false);
  }

  function setBadge(text, on) {
    $("live-badge").textContent = text;
    $("live-badge").className = "pill" + (on ? " on" : "");
  }

  /** Swaps in a new frame only once it has loaded, so the view never flashes empty. */
  function showFrame(runId, seq, url) {
    const next = new Image();
    next.onload = () => {
      $("live-frame").src = next.src;
      $("live-frame").alt = "Live view of the browser under test, showing " + (url || "the page");
      $("live-frame").hidden = false;
      $("live-placeholder").hidden = true;
    };
    next.src = "/api/runs/" + encodeURIComponent(runId) + "/live.jpg?frame=" + seq;
  }

  function renderPages(pages, current) {
    if (pages.length === 0) return;
    $("live-pages").replaceChildren(...pages.map((u) => {
      const now = u === current;
      const li = el("li", { className: now ? "current" : "", textContent: u });
      if (now) li.append(el("span", { className: "tag", textContent: "now" }));
      return li;
    }));
  }

  function renderSteps(steps) {
    const box = $("live-steps-box");
    const atBottom = box.scrollHeight - box.scrollTop - box.clientHeight < 24;
    const items = [];
    let scenario, url;
    for (const s of steps) {
      if (s.scenarioId !== scenario) {
        scenario = s.scenarioId;
        url = undefined;
        items.push(el("li", {}, el("span", { className: "scn", textContent: scenario || "Run Hound" })));
      }
      const li = el("li", {}, el("time", { dateTime: s.at, textContent: time(s.at) }), el("span", { textContent: s.label }));
      if (s.url !== url) li.append(el("span", { className: "url", textContent: s.url }));
      url = s.url;
      items.push(li);
    }
    $("live-steps").replaceChildren(...items);
    if (atBottom) box.scrollTop = box.scrollHeight;
  }

  /**
   * Polls the run and its live view about twice a second. The status region only announces when the
   * scenario changes or the run ends; the step, URL and frame update silently.
   */
  async function poll(runId) {
    const base = "/api/runs/" + encodeURIComponent(runId);
    let scenario = null, frameSeq = 0, lastStep = "", pagesKey = "";
    for (;;) {
      let state, live;
      try {
        [state, live] = await Promise.all([api(base), api(base + "/live")]);
      } catch (err) {
        $("status").textContent = "Lost track of the run: " + err.message;
        break;
      }
      $("progress").max = Math.max(state.total, 1);
      $("progress").value = state.completed;
      if (live.url) $("live-url").textContent = live.url;
      if (live.frameSeq !== frameSeq) {
        frameSeq = live.frameSeq;
        showFrame(runId, frameSeq, live.url);
      }
      const last = live.steps[live.steps.length - 1];
      const stepKey = last ? last.at + last.label + live.steps.length : "";
      if (stepKey !== lastStep) {
        lastStep = stepKey;
        renderSteps(live.steps);
      }
      // live.step is cleared when a scenario starts, so a previous scenario's step never lingers.
      $("live-step").textContent = live.step || (live.scenarioId ? "Starting “" + (live.scenarioTitle || live.scenarioId) + "”" : $("live-step").textContent);
      const key = live.pagesVisited.join(" ") + "|" + live.url + "|" + state.status;
      if (key !== pagesKey) {
        pagesKey = key;
        renderPages(live.pagesVisited, state.status === "running" ? live.url : null);
      }
      if (state.status === "running") {
        if (live.scenarioId && live.scenarioId !== scenario) {
          scenario = live.scenarioId;
          const n = Math.min(state.completed + 1, state.total);
          $("status").textContent = "Scenario " + n + " of " + state.total + ": " + (live.scenarioTitle || live.scenarioId);
          $("live-scenario").textContent = live.scenarioTitle || live.scenarioId;
          $("live-scenario-id").textContent = live.scenarioId;
          setBadge("Live", true);
        } else if (!scenario) {
          $("status").textContent = "Starting " + state.total + " scenario" + (state.total === 1 ? "" : "s") + "…";
        }
        await new Promise((r) => setTimeout(r, 500));
        continue;
      }
      setBadge(state.status === "done" ? "Finished" : "Stopped", false);
      $("live-url-label").textContent = "Last page";
      $("live-scenario-h").textContent = "Last scenario";
      if (frameSeq === 0) $("live-placeholder").textContent = "No frames were captured.";
      if (state.status === "error") {
        $("status").textContent = "The run failed: " + state.error;
        $("live-step").textContent = "The run failed";
      } else {
        $("status").textContent = "Done. " + state.report.findings.length + " finding" + (state.report.findings.length === 1 ? "" : "s") + ".";
        $("live-step").textContent = "Finished. The last frame is shown above.";
        showReport(runId, state.report);
      }
      break;
    }
    $("run-button").disabled = false;
  }

  const VISUAL_KINDS = ["frame", "gif", "card", "screenshot"];
  const KIND_NAMES = { frame: "Annotated screenshot", gif: "Recording", card: "Data card", screenshot: "Screenshot" };

  /** One piece of visual evidence: the image (linked to the full-size file), what it shows, and its facts. */
  function evidenceFigure(base, e) {
    const href = base + "artifacts/" + encodeURIComponent(e.path);
    const meta = [
      e.step ? "Step: " + e.step : "",
      e.url ? "Page: " + e.url : "",
      e.capturedAt ? "Captured: " + e.capturedAt : "",
      e.kind === "gif" && e.frames ? e.frames + " frames, " + (e.durationMs / 1000).toFixed(1) + " s" : "",
    ].filter(Boolean).join(" · ");
    const figure = el("figure", {},
      el("a", { href, target: "_blank", rel: "noopener" }, el("img", { src: href, alt: (KIND_NAMES[e.kind] || e.kind) + ": " + e.label, loading: "lazy" })),
      el("figcaption", {}, el("b", { textContent: (KIND_NAMES[e.kind] || e.kind) + ": " + e.label }), meta ? el("span", { textContent: " · " + meta }) : ""));
    const facts = e.facts || [];
    if (facts.length > 0) {
      const dl = el("dl", {});
      for (const x of facts) dl.append(el("dt", { textContent: x.label }), el("dd", { textContent: x.value }));
      figure.append(el("details", {}, el("summary", { textContent: "Data behind it (" + facts.length + ")" }), dl));
    }
    return figure;
  }

  function showReport(runId, report) {
    const out = $("report");
    const s = report.summary;
    const base = "/api/runs/" + encodeURIComponent(runId) + "/";
    out.replaceChildren(
      el("p", { textContent: s.passed + " passed, " + s.failed + " failed, " + s.errored + " errored, " + s.skipped + " skipped. Findings: " + s.critical + " critical, " + s.high + " high, " + s.medium + " medium, " + s.low + " low." }),
      el("ul", { className: "links" },
        el("li", {}, el("a", { href: base + "report.html", textContent: "Full report (HTML)" })),
        el("li", {}, el("a", { href: base + "report.md", textContent: "Markdown report" })),
        el("li", {}, el("a", { href: base + "report.json", textContent: "JSON report" }))),
    );
    if (report.findings.length === 0) out.append(el("p", { className: "pass", textContent: "No findings in the scenarios that ran." }));
    const sorted = [...report.findings].sort((a, b) => (SEVERITY_ORDER[a.severity] ?? 9) - (SEVERITY_ORDER[b.severity] ?? 9));
    for (const f of sorted) {
      const item = el("article", { className: "finding" },
        el("h3", { textContent: "[" + f.severity + "] " + f.title }),
        el("p", { className: "muted", textContent: f.checkId + (f.location ? " · " + f.location : "") }),
        el("p", { textContent: f.meaning }),
        el("p", { textContent: "Fix: " + f.fix }));
      const visual = (f.evidence || []).filter((e) => e.path && VISUAL_KINDS.includes(e.kind));
      if (visual.length > 0) item.append(el("div", { className: "evidence" }, ...visual.map((e) => evidenceFigure(base, e))));
      if (f.spec) item.append(el("p", {}, el("a", { href: base + "specs/" + encodeURIComponent(f.spec.filename), textContent: "Playwright spec: " + f.spec.filename })));
      out.append(item);
    }
    const errored = report.results.filter((r) => r.status === "error");
    for (const r of errored) out.append(el("p", { className: "error", textContent: r.scenarioId + " errored: " + (r.notes || "") }));
    out.append(el("h3", { textContent: "What a browser can't see" }), el("ul", {}, ...report.notVisible.map((t) => el("li", { textContent: t }))));
    $("report-section").hidden = false;
    $("report-section").focus();
  }

  // Reloading the page (or opening a link to #run=<id>) shows that run again: live while it runs, then its report.
  const resume = /^#run=([\\w-]+)$/.exec(location.hash);
  if (resume) {
    $("progress-section").hidden = false;
    resetLive(false);
    $("run-button").disabled = true;
    poll(resume[1]);
  }
})();
</script>
</body>
</html>
`;
