/**
 * Shared helpers for the accessibility and security checks (axe-states, keyboard-completion,
 * focus-visible, error-announcement, credential-fields, bundle-secrets, pii-leak, reflow-320).
 */
import type { Page } from "playwright";
import { cleanErrorMessage } from "../../engine/errors.js";
import { openFormSpec } from "../../engine/open-form.js";
import { redactSecrets } from "../../engine/redact.js";
import type {
  Category,
  CheckId,
  CheckResult,
  DiscoveredForm,
  Finding,
  FormField,
  Scenario,
} from "../../core/types.js";

/**
 * Runs `fnSource` (the source of a single arrow function) in the page with `arg`.
 * Passing source text keeps tsx/esbuild's `__name` helpers out of browser code.
 */
export async function evalIn<T>(page: Page, fnSource: string, arg?: unknown): Promise<T> {
  return page.evaluate(`(${fnSource})(${JSON.stringify(arg ?? null)})`) as Promise<T>;
}

export function scenarioFor(
  checkId: CheckId,
  suffix: string,
  fields: Pick<Scenario, "title" | "description"> & Partial<Pick<Scenario, "kind" | "priority">>,
): Scenario {
  return {
    id: `${checkId}:${suffix}`,
    checkId,
    title: fields.title,
    description: fields.description,
    kind: fields.kind ?? "golden",
    priority: fields.priority ?? "medium",
    destructive: false,
    defaultSelected: true,
  };
}

/** Builds findings with ids unique within one run of a check ("<checkId>#<n>"). */
export class FindingList {
  readonly items: Finding[] = [];
  constructor(
    private readonly checkId: CheckId,
    private readonly category: Category,
  ) {}

  add(finding: Omit<Finding, "checkId" | "id" | "category" | "confidence"> & { confidence?: Finding["confidence"] }): Finding {
    const full: Finding = {
      checkId: this.checkId,
      id: `${this.checkId}#${this.items.length + 1}`,
      category: this.category,
      confidence: finding.confidence ?? "confirmed",
      ...finding,
    };
    this.items.push(full);
    return full;
  }
}

export function checkResult(
  checkId: CheckId,
  scenario: Scenario,
  startedAt: number,
  findings: Finding[],
  notes?: string,
): CheckResult {
  return {
    checkId,
    scenarioId: scenario.id,
    status: findings.length > 0 ? "fail" : "pass",
    findings,
    durationMs: Date.now() - startedAt,
    ...(notes ? { notes } : {}),
  };
}

/** Wraps a check's run so unexpected exceptions become an "error" result with the message in notes. */
export async function guarded(
  checkId: CheckId,
  scenario: Scenario,
  body: (startedAt: number) => Promise<CheckResult>,
): Promise<CheckResult> {
  const startedAt = Date.now();
  try {
    return await body(startedAt);
  } catch (error) {
    return {
      checkId,
      scenarioId: scenario.id,
      status: "error",
      findings: [],
      durationMs: Date.now() - startedAt,
      // One plain line in the report: never Playwright's call log.
      notes: redactSecrets(cleanErrorMessage(error instanceof Error ? error.message : String(error))),
    };
  }
}

/**
 * A Playwright spec file that reproduces a finding. `body` is the test body (indented by the caller or not). When
 * `form` is in a dialog (an opener), the spec opens it after loading the page, the way the check did.
 */
export function playwrightSpec(
  checkId: CheckId,
  findingNo: number,
  testTitle: string,
  targetUrl: string,
  body: string,
  extraImports: string[] = [],
  form?: DiscoveredForm,
) {
  const indented = [...(form ? openFormSpec(form) : []), ...body.trim().split("\n")]
    .map((line) => (line ? `  ${line}` : line))
    .join("\n");
  return {
    filename: `${checkId}-${findingNo}.spec.ts`,
    source: `import { test, expect } from "@playwright/test";
${extraImports.map((line) => `${line}\n`).join("")}
// Generated by Run Hound (${checkId}). Fails while the problem is present.
const TARGET = ${JSON.stringify(targetUrl)};

test(${JSON.stringify(testTitle)}, async ({ page }) => {
  await page.goto(TARGET, { waitUntil: "networkidle" });
${indented}
});
`,
  };
}

/** Human name for a field, as a user would describe it. */
export function fieldName(field: FormField): string {
  return field.label ?? field.accessibleName ?? field.placeholder ?? field.key;
}

export function submitControl(form: DiscoveredForm) {
  return form.controls.find((c) => c.isSubmit) ?? null;
}

/** Attribute Run Hound puts on the focused element so evidence frames can mark it by selector. */
const FOCUS_MARK = "data-rh-focus";

/**
 * Tags the element that has keyboard focus (and untags any earlier one) and returns a selector for it, or null when
 * focus is on the page body. Only an attribute changes; nothing visible does.
 */
export async function markFocused(page: Page): Promise<string | null> {
  const marked = await evalIn<boolean>(
    page,
    `(attr) => {
      for (const el of document.querySelectorAll("[" + attr + "]")) el.removeAttribute(attr);
      const el = document.activeElement;
      if (!el || el === document.body || el === document.documentElement) return false;
      el.setAttribute(attr, "");
      return true;
    }`,
    FOCUS_MARK,
  );
  return marked ? `[${FOCUS_MARK}]` : null;
}

/** Shortens `text` to `max` characters with an ellipsis, for facts and callouts. */
export function clip(text: string, max = 120): string {
  const flat = text.replace(/\s+/g, " ").trim();
  return flat.length > max ? `${flat.slice(0, max - 1)}…` : flat;
}

/**
 * Names for the places one grouped finding covers, each listed once: a name shared by two elements gets the
 * element's selector added ("Remove (#remove-2)"), and a number if that is still not enough.
 */
export function uniquePlaces(items: { name: string; selector?: string }[]): string[] {
  const counts = new Map<string, number>();
  for (const { name } of items) counts.set(name, (counts.get(name) ?? 0) + 1);
  const used = new Set<string>();
  return items.map(({ name, selector }) => {
    let place = (counts.get(name) ?? 0) > 1 && selector ? `${name} (${selector})` : name;
    for (let n = 2; used.has(place); n++) place = `${name} (${n})`;
    used.add(place);
    return place;
  });
}

/** "3 controls" / "1 control". */
export function plural(n: number, one: string, many = `${one}s`): string {
  return `${n} ${n === 1 ? one : many}`;
}

/** "a", "a and b", "a, b and c" (quoted with `quote`), cut after `max` items with "and N more". */
export function listOf(items: string[], max = 6, quote = (s: string) => `"${s}"`): string {
  const shown = items.slice(0, max).map(quote);
  const rest = items.length - shown.length;
  if (rest > 0) return `${shown.join(", ")} and ${rest} more`;
  if (shown.length <= 1) return shown.join("");
  return `${shown.slice(0, -1).join(", ")} and ${shown[shown.length - 1]}`;
}
