/**
 * Shared helpers for the accessibility and security checks (axe-states, keyboard-completion,
 * focus-visible, error-announcement, credential-fields, bundle-secrets, pii-leak, reflow-320).
 */
import type { Page } from "playwright";
import { redactSecrets } from "../../engine/redact.js";
import type {
  Category,
  CheckId,
  CheckResult,
  DiscoveredForm,
  Finding,
  FormField,
  Scenario,
} from "../../core/types.js";

/**
 * Runs `fnSource` (the source of a single arrow function) in the page with `arg`.
 * Passing source text keeps tsx/esbuild's `__name` helpers out of browser code.
 */
export async function evalIn<T>(page: Page, fnSource: string, arg?: unknown): Promise<T> {
  return page.evaluate(`(${fnSource})(${JSON.stringify(arg ?? null)})`) as Promise<T>;
}

export function scenarioFor(
  checkId: CheckId,
  suffix: string,
  fields: Pick<Scenario, "title" | "description"> & Partial<Pick<Scenario, "kind" | "priority">>,
): Scenario {
  return {
    id: `${checkId}:${suffix}`,
    checkId,
    title: fields.title,
    description: fields.description,
    kind: fields.kind ?? "golden",
    priority: fields.priority ?? "medium",
    destructive: false,
    defaultSelected: true,
  };
}

/** Builds findings with ids unique within one run of a check ("<checkId>#<n>"). */
export class FindingList {
  readonly items: Finding[] = [];
  constructor(
    private readonly checkId: CheckId,
    private readonly category: Category,
  ) {}

  add(finding: Omit<Finding, "checkId" | "id" | "category" | "confidence"> & { confidence?: Finding["confidence"] }): Finding {
    const full: Finding = {
      checkId: this.checkId,
      id: `${this.checkId}#${this.items.length + 1}`,
      category: this.category,
      confidence: finding.confidence ?? "confirmed",
      ...finding,
    };
    this.items.push(full);
    return full;
  }
}

export function checkResult(
  checkId: CheckId,
  scenario: Scenario,
  startedAt: number,
  findings: Finding[],
  notes?: string,
): CheckResult {
  return {
    checkId,
    scenarioId: scenario.id,
    status: findings.length > 0 ? "fail" : "pass",
    findings,
    durationMs: Date.now() - startedAt,
    ...(notes ? { notes } : {}),
  };
}

/** Wraps a check's run so unexpected exceptions become an "error" result with the message in notes. */
export async function guarded(
  checkId: CheckId,
  scenario: Scenario,
  body: (startedAt: number) => Promise<CheckResult>,
): Promise<CheckResult> {
  const startedAt = Date.now();
  try {
    return await body(startedAt);
  } catch (error) {
    return {
      checkId,
      scenarioId: scenario.id,
      status: "error",
      findings: [],
      durationMs: Date.now() - startedAt,
      notes: redactSecrets(error instanceof Error ? error.message : String(error)),
    };
  }
}

/** A Playwright spec file that reproduces a finding. `body` is the test body (indented by the caller or not). */
export function playwrightSpec(
  checkId: CheckId,
  findingNo: number,
  testTitle: string,
  targetUrl: string,
  body: string,
  extraImports: string[] = [],
) {
  const indented = body
    .trim()
    .split("\n")
    .map((line) => (line ? `  ${line}` : line))
    .join("\n");
  return {
    filename: `${checkId}-${findingNo}.spec.ts`,
    source: `import { test, expect } from "@playwright/test";
${extraImports.map((line) => `${line}\n`).join("")}
// Generated by Run Hound (${checkId}). Fails while the problem is present.
const TARGET = ${JSON.stringify(targetUrl)};

test(${JSON.stringify(testTitle)}, async ({ page }) => {
  await page.goto(TARGET, { waitUntil: "networkidle" });
${indented}
});
`,
  };
}

/** Human name for a field, as a user would describe it. */
export function fieldName(field: FormField): string {
  return field.label ?? field.accessibleName ?? field.placeholder ?? field.key;
}

export function submitControl(form: DiscoveredForm) {
  return form.controls.find((c) => c.isSubmit) ?? null;
}
